# Generated by Django 4.0.3 on 2022-06-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=20)),
                ('edu_major', models.CharField(max_length=20)),
                ('edu_exp', models.CharField(max_length=20)),
                ('edu_course_1', models.CharField(max_length=20)),
                ('edu_course_2', models.CharField(max_length=20)),
            ],
        ),
    ]
